name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/ -v

      - name: Test Flask app starts
        run: |
          python -c "import app; print('Flask app imports successfully')"

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t seniors-website:latest .

      - name: Test Docker image
        run: |
          docker run -d -p 5000:5000 --name test-container seniors-website:latest
          sleep 10
          curl -f http://localhost:5000/ || exit 1
          docker stop test-container
          docker rm test-container

      - name: Deploy to Render (if configured)
        if: env.RENDER_API_KEY
        run: |
          echo "Deployment to Render would happen here"
          # Add actual Render deployment commands if you set up Render
